name: Build QA App

on: 
 workflow_dispatch:
 
jobs: 
 deploy_ios:
   name: 🍏📦🚀 Build & deploy iOS QA
   runs-on: macos-latest
   steps:
     - name: ⬇️ Checkout repository
       uses: actions/checkout@v4
       with:
         ref: qa
     - name: 🔐 Install Apple certificate and provisioning profile
       env:
         P12_DISTRIBUTION_CERTIFICATE_BASE64: "${{ secrets.IOS_P12_DISTRIBUTION_CERTIFICATE_BASE64 }}"
         P12_DISTRIBUTION_CERTIFICATE_PASSWORD: "${{ secrets.IOS_P12_DISTRIBUTION_CERTIFICATE_PASSWORD }}"
         DISTRIBUTION_PROVISIONING_PROFILE_BASE64: "${{ secrets.IOS_QA_DISTRIBUTION_PROVISIONING_PROFILE_BASE64 }}"
         KEYCHAIN_PASSWORD: "${{ secrets.IOS_RUNNER_LOCAL_KEYCHAIN_PASSWORD }}"
         EXPORT_OPTIONS_BASE64: "${{ secrets.IOS_QA_EXPORT_OPTIONS_BASE64 }}"
       run: |
         # all dat shiz
         echo "creating variables"
         CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
         PROVISIONING_PROFILE_PATH=$RUNNER_TEMP/build_pp.mobileprovision
         KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
         EXPORT_OPTIONS_PATH="${{ github.workspace }}/ios/Runner/ExportOptions.plist"

         echo "importing certificate, provisioning profile and export options from secrets"
         echo -n "$P12_DISTRIBUTION_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
         echo -n "$DISTRIBUTION_PROVISIONING_PROFILE_BASE64" | base64 --decode -o $PROVISIONING_PROFILE_PATH
         echo -n "$EXPORT_OPTIONS_BASE64" | base64 --decode -o $EXPORT_OPTIONS_PATH

         echo "creating temporary keychain"
         security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
         security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
         security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

         echo "importing certificate to keychain"
         security import $CERTIFICATE_PATH -P "$P12_DISTRIBUTION_CERTIFICATE_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
         security list-keychain -d user -s $KEYCHAIN_PATH

         echo "applying provisioning profile"
         mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
         cp $PROVISIONING_PROFILE_PATH ~/Library/MobileDevice/Provisioning\ Profiles
     - name: ⚙️ Setup Flutter
       uses: subosito/flutter-action@v2
       with:
         flutter-version: "3.16.7"
         channel: 'stable'
         cache: true
       id: flutter
     - name: 🍏📦 Create iOS appbundle release
       run: |
         flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions.plist
     - name: 📦 List App Bundle directory
       run: |
         ls -al /Users/runner/work/TaskRM/TaskRM/build/ios/ipa/
     - name: 🍏🚀 Deploy to App Store (Testflight)
       uses: apple-actions/upload-testflight-build@v1
       with:
         app-path: ${{ github.workspace }}/build/ios/ipa/TaskRMQA.ipa
         issuer-id: ${{ secrets.IOS_APP_STORE_CONNECT_ISSUER_ID }}
         api-key-id: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY_ID }}
         api-private-key: ${{ secrets.IOS_APP_STORE_CONNECT_API_PRIVATE_KEY }}