name: Build Android App

on: 
 workflow_dispatch:
 
# A single workflow can have multiple jobs.
jobs: 
    # 'A new job is defined with the name: "build_android" 
    build_android:
      # Defines what operating system will be used for the actions.
      # For android, we will use Linux GitHub-Hosted Runner.
      runs-on: ubuntu-22.04
      # Defines what step should be passed for successful run
      steps:
        # Checkout to the selected branch
        - name: Checkout
          uses: actions/checkout@v3
        # Download and install flutter packages
        - name: Install Flutter
          uses: subosito/flutter-action@v2
          with:
            # Define which stable flutter version should be used
            flutter-version: "3.16.7"
            channel: 'stable'
            # Enables cache for flutter packages              
            # Speed up the process
            cache: true
        # Get Flutter project dependencies
        - name: Get dependencies
          run: flutter pub get
        # Update Flutter application bundle
        - name: Build release app bundle
          run: flutter build appbundle
        # Sign the bundle
        - name: Sign App Bundle
          uses: r0adkll/sign-android-release@v1   
          id: sign_app
          with:
            releaseDirectory: build/app/outputs/bundle/release/
            signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}
            alias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}         
            keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}             
            keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
        - name: Upload Signed App Bundle
          uses: actions/upload-artifact@v3
          with:
            name: signed-app-bundle
            path: ${{steps.sign_app.outputs.signedReleaseFile}}